### ISSUE TITLE
ReCaptcha doesn't work

### ISSUE THREAD

**Issue by Wargog** [austinkregel/php-login-advanced#7]
After defining my recaptcha keys in the config file it doesn't display a captcha, or anything except the form for that matter.

**Comment by austinkregel** [comment]
Okay, do you see any error messages in your javascript console? (`F12` on IE, `Ctrl + Shift + J` on chrome, or `Ctrl + Shift + K` on FireFox.)? If not make sure you have the following inside your config file

```
define('RECAPTCHA_SECRETKEY', 'Your secret key');
define('RECAPTCHA_SITEKEY', 'Your site key');
```

It looks like those are not defined in the recent config files for any current fork and I don't know why.

**Comment by Wargog** [comment]
No JavaScript errors, yes both keys were defined.

**Comment by austinkregel** [comment]
Are you running the most recent version of the script? If so, which version of the project are you using?

**Comment by Wargog** [comment]
Yes, I'm running bootstrap-master on my fork, but I haven't changed
anything related to captchas other than putting the option for the keys in
the config

**Comment by austinkregel** [comment]
Are you on the registration page, because that is the only page set up for reCaptcha. If you are on the registration page, are you seeing a red message appear where there is suppose to be the captcha? something similar to "ERROR: Invalid domain for site key"? Or are you literally seeing nothing. If you're not seeing anything then update your project to the most recent version to 1.0.1

**Comment by Wargog** [comment]
I'm not seeing anything, it is running off of the latest commit to the
bootstrap branch. There are no PHP errors or JavaScript errors or the box
that says invalid key

**Comment by austinkregel** [comment]
Okay so I am assuming you're trying to register a new user. I recommend updating to the latest commit (done within the past hour) and double checking the registration page. I just updated my [test setup](http://php-login.austinkregel.com/bootstrap-master/?register), and everything is working accordingly.

**Comment by Wargog** [comment]
OK, will do I'll let you know

**Comment by Wargog** [comment]
Updated to latest bootstrap-master from your branch, still no captcha. http://gyazo.com/ef61b5fa1fb7c5f077283b6f05497e61

**Comment by austinkregel** [comment]
That's really interesting.... If you were to inspect the element (in between the register button and the password repeat section) do you see the div tag for recaptcha? If so then check the css on it because there might be something that is overriding it's CSS. If you can't see it when you inspect the element then you will have to edit the register view.

**Comment by Wargog** [comment]
The div is there, however something is hiding it, I haven't the slightest idea what though.

**Comment by Wargog** [comment]
It's not even loading the stuff from the API, it's just putting the div there but never receiving anything for it to display the actual cpatcha

**Comment by austinkregel** [comment]
Okay so do you have the required js script in the file? `https://www.google.com/recaptcha/api.js`

**Comment by Wargog** [comment]
That would be it! Forgot all about that! Thank you.

**Comment by austinkregel** [comment]
You're welcome, sorry about this taking so long! I was really scratching my head as to what it could be then I remembered that it requires a js file! 

I'm glad we figured it out!

**Comment by Wargog** [comment]
Me too haha, if you need any help with the custom config thing I requested
just let me know.
